name: SpO2
description: A new Flutter project. Created by Slidy

publish_to: 'none'

version: 1.0.0+1

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera:
    git:
      url: https://github.com/felipesses/camera-repo.git
  device_info: ">=0.4.2+7 <2.0.0"
  dio: ^3.0.10
  ffi: ^0.1.3
  fft: ^0.3.0
  firebase_core: ^0.5.2+1
  firebase_database: ^4.3.0
  flutter_launcher_icons: ^0.8.1
  flutter_mobx: ^1.1.0+2
  flutter_modular: ^2.0.1
  image: ^2.1.19
  mobx: ^1.2.1+4
  uuid: ^2.2.2
  wakelock: ^0.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  mobx_codegen: ^1.1.2
  mockito: ^4.1.3
  modular_codegen: ^2.0.1

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/launcher.png"
  image_path_android: "assets/images/launcher.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
